#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''test_authdb.py - Waqas Bhatti (wbhatti@astro.princeton.edu) - Aug 2018
License: MIT - see the LICENSE file for the full text.

This tests lccserver.authnzerver.authdb.py.

'''

import pytest

from lccserver.authnzerver import authdb


def test_check_user_access_default():
    '''This validates that check_user_access denies by default if called w/o
    kwargs.

    '''

    # default policy is deny
    assert authdb.check_user_access() is False


######################
## ANONYMOUS ACCESS ##
######################

@pytest.mark.parametrize(
    "access,target,expected", [
        # anonymous -> self-owned public collection
        ((2, 'anonymous', 'list'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('collection', 2, 'public', ''),
         False),
        # anonymous -> public collection from others
        ((2, 'anonymous', 'list'),
         ('collection', 1, 'public', ''),
         True),
        ((2, 'anonymous', 'view'),
         ('collection', 1, 'public', ''),
         True),
        ((2, 'anonymous', 'create'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('collection', 1, 'public', ''),
         False),
        # anonymous -> shared collection from others
        ((2, 'anonymous', 'list'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        # anonymous -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'anonymous', 'list'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('collection', 1, 'shared', '5,6'),
         False),
        # anonymous -> private collection from others
        ((2, 'anonymous', 'list'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('collection', 1, 'private', ''),
         False),
    ]
)
def test_check_anonymous_access_to_collection(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # anonymous -> self-owned public dataset
        ((2, 'anonymous', 'list'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'anonymous', 'view'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'anonymous', 'create'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'anonymous', 'edit'),
         ('dataset', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('dataset', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('dataset', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('dataset', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('dataset', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('dataset', 2, 'public', ''),
         False),
        # anonymous -> public dataset from others
        ((2, 'anonymous', 'list'),
         ('dataset', 1, 'public', ''),
         True),
        ((2, 'anonymous', 'view'),
         ('dataset', 1, 'public', ''),
         True),
        ((2, 'anonymous', 'create'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('dataset', 1, 'public', ''),
         False),
        # anonymous -> shared dataset from others
        ((2, 'anonymous', 'list'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        # anonymous -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'anonymous', 'list'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        # anonymous -> private dataset from others
        ((2, 'anonymous', 'list'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('dataset', 1, 'private', ''),
         False),
    ]
)
def test_check_anonymous_access_to_dataset(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # anonymous -> self-owned public object (should all fail)
        ((2, 'anonymous', 'list'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('object', 2, 'public', ''),
         False),
        # anonymous -> public object from others (list, view OK)
        ((2, 'anonymous', 'list'),
         ('object', 1, 'public', ''),
         True),
        ((2, 'anonymous', 'view'),
         ('object', 1, 'public', ''),
         True),
        ((2, 'anonymous', 'create'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('object', 1, 'public', ''),
         False),
        # anonymous -> shared object from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        # anonymous -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'anonymous', 'list'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('object', 1, 'shared', '5,6'),
         False),
        # anonymous -> private object from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('object', 1, 'private', ''),
         False),
    ]
)
def test_check_anonymous_access_to_object(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # anonymous -> self-owned public users (should all fail)
        ((2, 'anonymous', 'list'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('users', 2, 'public', ''),
         False),
        # anonymous -> public users from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('users', 1, 'public', ''),
         False),
        # anonymous -> shared users from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        # anonymous -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'anonymous', 'list'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('users', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('users', 1, 'shared', '5,6'),
         False),
        # anonymous -> private users from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('users', 1, 'private', ''),
         False),
    ]
)
def test_check_anonymous_access_to_users(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # anonymous -> self-owned public apikeys (should all fail)
        ((2, 'anonymous', 'list'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('apikeys', 2, 'public', ''),
         False),
        # anonymous -> public apikeys from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('apikeys', 1, 'public', ''),
         False),
        # anonymous -> shared apikeys from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        # anonymous -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'anonymous', 'list'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('apikeys', 1, 'shared', '5,6'),
         False),
        # anonymous -> private apikeys from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('apikeys', 1, 'private', ''),
         False),
    ]
)
def test_check_anonymous_access_to_apikeys(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # anonymous -> self-owned public preferences (should all fail)
        ((2, 'anonymous', 'list'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('preferences', 2, 'public', ''),
         False),
        # anonymous -> public preferences from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('preferences', 1, 'public', ''),
         False),
        # anonymous -> shared preferences from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        # anonymous -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'anonymous', 'list'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'view'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'create'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'edit'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'delete'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_public'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'make_private'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('preferences', 1, 'shared', '5,6'),
         False),
        # anonymous -> private preferences from others (should all fail)
        ((2, 'anonymous', 'list'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'view'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'create'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'edit'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'delete'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_public'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_shared'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'make_private'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'anonymous', 'change_owner'),
         ('preferences', 1, 'private', ''),
         False),
    ]
)
def test_check_anonymous_access_to_preferences(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



##########################
## AUTHENTICATED ACCESS ##
##########################

@pytest.mark.parametrize(
    "access,target,expected", [
        # authenticated -> self-owned public collection
        ((2, 'authenticated', 'list'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('collection', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('collection', 2, 'public', ''),
         False),
        # authenticated -> public collection from others
        ((2, 'authenticated', 'list'),
         ('collection', 1, 'public', ''),
         True),
        ((2, 'authenticated', 'view'),
         ('collection', 1, 'public', ''),
         True),
        ((2, 'authenticated', 'create'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('collection', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('collection', 1, 'public', ''),
         False),
        # authenticated -> shared collection from others
        ((2, 'authenticated', 'list'),
         ('collection', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'view'),
         ('collection', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'create'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('collection', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'delete'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('collection', 1, 'shared', '2,5,6'),
         False),
        # authenticated -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'authenticated', 'list'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'view'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'create'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'delete'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('collection', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('collection', 1, 'shared', '5,6'),
         False),
        # authenticated -> private collection from others
        ((2, 'authenticated', 'list'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('collection', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('collection', 1, 'private', ''),
         False),
    ]
)
def test_check_authenticated_access_to_collection(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # authenticated -> self-owned public dataset
        ((2, 'authenticated', 'list'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'view'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'create'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'edit'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'delete'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'make_public'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'make_shared'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'make_private'),
         ('dataset', 2, 'public', ''),
         True),
        ((2, 'authenticated', 'change_owner'),
         ('dataset', 2, 'public', ''),
         False),
        # authenticated -> public dataset from others
        ((2, 'authenticated', 'list'),
         ('dataset', 1, 'public', ''),
         True),
        ((2, 'authenticated', 'view'),
         ('dataset', 1, 'public', ''),
         True),
        ((2, 'authenticated', 'create'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('dataset', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('dataset', 1, 'public', ''),
         False),
        # authenticated -> shared dataset from others
        ((2, 'authenticated', 'list'),
         ('dataset', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'view'),
         ('dataset', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'create'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('dataset', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'delete'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('dataset', 1, 'shared', '2,5,6'),
         False),
        # authenticated -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'authenticated', 'list'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'view'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'create'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'delete'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('dataset', 1, 'shared', '5,6'),
         False),
        # authenticated -> private dataset from others
        ((2, 'authenticated', 'list'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('dataset', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('dataset', 1, 'private', ''),
         False),
    ]
)
def test_check_authenticated_access_to_dataset(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # authenticated -> self-owned public object (should all fail)
        ((2, 'authenticated', 'list'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('object', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('object', 2, 'public', ''),
         False),
        # authenticated -> public object from others (list, view OK)
        ((2, 'authenticated', 'list'),
         ('object', 1, 'public', ''),
         True),
        ((2, 'authenticated', 'view'),
         ('object', 1, 'public', ''),
         True),
        ((2, 'authenticated', 'create'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('object', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('object', 1, 'public', ''),
         False),
        # authenticated -> shared from others (list, view, edit OK)
        ((2, 'authenticated', 'list'),
         ('object', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'view'),
         ('object', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'create'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('object', 1, 'shared', '2,5,6'),
         True),
        ((2, 'authenticated', 'delete'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('object', 1, 'shared', '2,5,6'),
         False),
        # authenticated -> shared from others but not shared to this
        # user (should all fail)
        ((2, 'authenticated', 'list'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'view'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'create'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'delete'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('object', 1, 'shared', '5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('object', 1, 'shared', '5,6'),
         False),
        # authenticated -> private object from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('object', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('object', 1, 'private', ''),
         False),
    ]
)
def test_check_authenticated_access_to_object(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # authenticated -> self-owned public users (should all fail)
        ((2, 'authenticated', 'list'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('users', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('users', 2, 'public', ''),
         False),
        # authenticated -> public users from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('users', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('users', 1, 'public', ''),
         False),
        # authenticated -> shared users from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'view'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'create'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'delete'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('users', 1, 'shared', '2,5,6'),
         False),
        # authenticated -> private users from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('users', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('users', 1, 'private', ''),
         False),
    ]
)
def test_check_authenticated_access_to_users(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # authenticated -> self-owned public apikeys (should all fail)
        ((2, 'authenticated', 'list'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('apikeys', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('apikeys', 2, 'public', ''),
         False),
        # authenticated -> public apikeys from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('apikeys', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('apikeys', 1, 'public', ''),
         False),
        # authenticated -> shared apikeys from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'view'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'create'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'delete'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('apikeys', 1, 'shared', '2,5,6'),
         False),
        # authenticated -> private apikeys from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('apikeys', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('apikeys', 1, 'private', ''),
         False),
    ]
)
def test_check_authenticated_access_to_apikeys(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected



@pytest.mark.parametrize(
    "access,target,expected", [
        # authenticated -> self-owned public preferences (should all fail)
        ((2, 'authenticated', 'list'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('preferences', 2, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('preferences', 2, 'public', ''),
         False),
        # authenticated -> public preferences from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('preferences', 1, 'public', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('preferences', 1, 'public', ''),
         False),
        # authenticated -> shared preferences from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'view'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'create'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'edit'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'delete'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_public'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'make_private'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('preferences', 1, 'shared', '2,5,6'),
         False),
        # authenticated -> private preferences from others (should all fail)
        ((2, 'authenticated', 'list'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'view'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'create'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'edit'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'delete'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_public'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_shared'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'make_private'),
         ('preferences', 1, 'private', ''),
         False),
        ((2, 'authenticated', 'change_owner'),
         ('preferences', 1, 'private', ''),
         False),
    ]
)
def test_check_authenticated_access_to_preferences(access, target, expected):
    '''
    This checks user access.

    '''
    userid, role, action = access
    target_name, target_owner, target_visibility, target_sharedwith = target

    assert authdb.check_user_access(
        userid=userid,
        role=role,
        action=action,
        target_name=target_name,
        target_owner=target_owner,
        target_visibility=target_visibility,
        target_sharedwith=target_sharedwith
    ) is expected
